version: '3.7'
services:
  mysql:
    image: mysql:8.0
    ports:
      - '3306:3306'
    volumes:
      - ./mysql_artifacts/schema.sql:/docker-entrypoint-initdb.d/a.sql
    restart: always
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app
      - MYSQL_USER=vasya
      - MYSQL_PASSWORD=qwerty123